# Visit https://alacritty.org/config-alacritty.html for detailed information

[general]
import = [
	# Import theme.toml file
	# I'm using Nord theme for Alacritty. You can download it from https://github.com/alacritty/alacritty-theme/blob/master/themes/nord.toml
    "C:\\Users\\<username>\\AppData\\Roaming\\alacritty\\themes\\nord.toml"
]

# This might not work on every system
# Alternatively just add the absolute path to your home folder
# Something like "C:\\Users\\<username>"
working_directory="$HOME"

[terminal]
# Currently using PowerShell 7 as default shell
# Make sure PowerShell 7 is installed. Visit this site for installation https://learn.microsoft.com/en-us/powershell/scripting/install/install-powershell-on-windows?view=powershell-7.5#msi
shell = { program="C:\\Program Files\\PowerShell\\7\\pwsh.exe", args=["-NoLogo"] }

# Uncomment below to use PowerShell 5.1 as default shell
# shell = { program="C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", args=["-NoLogo"] }

[window]
dimensions = { columns=85, lines=25 }
opacity = 0.90
padding = { x = 4, y = 4 }

[font]
size = 11

normal = { family="Cascadia Mono NF", style="Regular" }
bold = { family="Cascadia Mono NF", style="Bold" }
italic = { family="Cascadia Mono NF", style="Italic" }
bold_italic = { family="Cascadia Mono NF", style="Bold Italic" }

offset.x = 0
offset.y = 4

[cursor]
style = { shape = "Block", blinking = "On"}
blink_interval = 500
blink_timeout = 0
